### ISSUE TITLE
Question/Contact for project inclusion in blog

### ISSUE THREAD

**Issue by kevinaboos** [rust-embedded/blog#185]
Hello fellow embedded rustaceans!

Not sure if this is the right place for this, but I saw [the latest This Year in Embedded Rust blog post](https://blog.rust-embedded.org/this-year-in-embedded-rust-2021/) on reddit last week and was excited to read the updates. The post mentioned contacting you all if we had other projects that could be included in the list, and I believe our project [Theseus OS](https://github.com/theseus-os/Theseus/) could merit inclusion since we have made some fairly significant changes in 2021. We've also spent a while contributing to various open-source `no_std` projects throughout the Rust community, some of which aren't necessarily embedded in nature but could prove useful in embedded environments.

Let me know if there's someone else I should contact about this; apologies if this is off-topic.

Best,
Kevin Boos

**Comment by eldruin** [comment]
Hi and happy new year!
Theseus OS definitely sounds interesting! Since it targets embedded systems (albeit high-end) I would say it fits.
It would be great if you could just open a PR adding an entry to the [next newsletter](https://github.com/rust-embedded/blog/blob/master/content/newsletter-next.md) whenever you have updates.
Please feel free to also add entries about other embedded projects whenever significant changes happened.

**Comment by kevinaboos** [comment]
Thanks very much, and happy new year to you too! 

I'll be sure to add updates to the next newsletter post when they happen.

**Comment by adamgreig** [comment]
@kevinaboos We keep the draft of the next newsletter open all the time, so you can PR edits to https://github.com/rust-embedded/blog/blob/master/content/newsletter-next.md whenever you like and they'll be included in the next release.

**Comment by kevinaboos** [comment]
Good to know, thanks!
